; This is a sample configuration file
; Comments start with ';'

[database]
dsn = "sqlite:{{ROOT_DIR}}/var/data/db.sqlite3"

[app]
name = "MotoGP"
version = "1.0.0"
season = "2026"

[log]
path = "{{ROOT_DIR}}/var/log/app.log"
level = "debug"
days = 30

[template]
dir = "{{ROOT_DIR}}/templates"
partials_dir = "{{ROOT_DIR}}/templates/partials"
cache = "{{ROOT_DIR}}/var/cache/mustache"
