; This is a sample configuration file
; Comments start with ';'

[database]
dsn = "sqlite:/Users/brett/gitrepos/motogp/db/db.sqlite3"

[app]
name = "MotoGP"
version = "1.0.0"
season = "2026"

[log]
path = "/Users/brett/gitrepos/motogp/var/log/app.log"
level = "debug"

[template]
dir = "/Users/brett/gitrepos/motogp/templates"
partials_dir = "/Users/brett/gitrepos/motogp/templates/partials"
cache = "/Users/brett/gitrepos/motogp/var/cache/mustache"
