delete from riders;
insert into riders (rider_id, name, active) values
(1, 'Jorge Martin', 1),
(2, 'Johann Zarco', 1),
(3, 'Luca Marini', 1),
(4, 'Maverick Viñales', 1),
(5, 'Fabio Quartararo', 1),
(6, 'Franco Morbidelli', 1),
(7, 'Enea Bastianini', 1),
(8, 'Raul Fernandez', 1),
(9, 'Brad Binder', 1),
(10, 'Somkiat Chantra', 1),
(11, 'Joan Mir', 1),
(12, 'Pedro Acosta', 1),
(13, 'Alex Rins', 1),
(14, 'Jack Miller', 1),
(15, 'Fabio Di Giannantonio', 1),
(16, 'Fermin Aldeguer', 1),
(17, 'Francesco Bagnaia', 1),
(18, 'Marco Bezzecchi', 1),
(19, 'Alex Marquez', 1),
(20, 'Ai Ogura', 1),
(21, 'Miguel Oliveira', 1),
(22, 'Marc Marquez', 1),
(23, 'Lorenzo Savadori', 1),
(24, 'Andrea Dovizioso', 1),
(25, 'Augusto Fernandez', 1),
(26, 'Dani Pedrosa', 1),
(27, 'Takaaki Nakagami', 1),
(28, 'Aleix Espargaro', 1),
(29, 'Pol Espargaro', 1),
(30, 'Michele Pirro', 1);
